Repository dpc-sdp/tide_core, pull requests merged in 2019-08, with the labels that each got.

#79 [SDPA-2742] remove scheduled_updates module
  composer.json
  config/install/core.entity_form_display.scheduled_update.scheduled_archiving.default.yml
  config/install/core.entity_form_display.scheduled_update.scheduled_publishing.default.yml
  config/install/field.field.scheduled_update.scheduled_archiving.field_moderation_state_archived.yml
  config/install/field.field.scheduled_update.scheduled_publishing.field_moderation_state_published.yml
  config/install/field.storage.node.scheduled_archiving.yml
  config/install/field.storage.node.scheduled_publishing.yml
  config/install/field.storage.scheduled_update.field_moderation_state_archived.yml
  config/install/field.storage.scheduled_update.field_moderation_state_published.yml
  config/install/scheduled_updates.scheduled_update_type.scheduled_archiving.yml
  config/install/scheduled_updates.scheduled_update_type.scheduled_publishing.yml
  config/install/user.role.approver.yml
  config/install/user.role.site_admin.yml
  tests/behat/features/clamav.feature
  tests/behat/features/scheduled_updates.feature
  tide_core.info.yml
  tide_core.install
  tide_core.module
Labels: NEEDS REVIEW

#82 Changed %uid token to %user in login redirect URL of PRLP settings.
  config/optional/prlp.settings.yml
  tide_core.install
Labels: NEEDS REVIEW

#83 Added Pathauto pattern for Topic and Tags.
  config/optional/pathauto.pattern.taxonomy_term.yml
  tide_core.install
Labels: NEEDS REVIEW

#75 [SDPA-1395] updates date format to d-m-Y
  composer.json
Labels: Ready for test

#87 [SDPA-3100]Altered the scheduled transition’s UI
  composer.json
  config/optional/workflows.workflow.editorial.yml
  src/EventSubscriber/TideCoreRouteAlter.php
  tide_core.install
  tide_core.links.task.yml
  tide_core.module
  tide_core.services.yml
Labels: NEEDS REVIEW, question
