Repository dpc-sdp/tide_core, pull requests merged in 2020-08, with the labels that each got.

#160 [SDPA-4332] WYSIWYG media picker creating duplicate entries
  composer.json
Labels: Ready to be merged

#156 [SDPA-4357] Deletion and replacement of unsupported actions.
  config/install/system.action.tide_core_archive.yml
  config/install/system.action.tide_core_publish.yml
  src/Form/NodeActionForm.php
  src/Plugin/Action/TideCoreArchiveAction.php
  src/Plugin/Action/TideCoreBaseAction.php
  src/Plugin/Action/TideCorePublishAction.php
  tide_core.install
  tide_core.routing.yml
Labels: Ready to be merged

#161 [SDPA-4193] moves introduction up to top
  tide_core.install
Labels: Needs review

#164 [SW-320] Added patch for entity embed module.
  composer.json
Labels: Needs review

#163 [SDPA-4091] changes allowed HTML list
  config/install/filter.format.admin_text.yml
  config/install/filter.format.rich_text.yml
  tide_core.install
Labels: DO NOT MERGE

#168 [SDPA-2970] change display of dates in CMS to Australian style DD/MM/YYYY
  tide_core.install
Labels: Ready for test

#165 [SDPA-4661] enable addtional contact block
  config/install/field.storage.node.field_landing_page_contact.yml
  tide_core.install
Labels: Ready for test

#167 [SDPA-4329] cms improvements accordin
  config/install/core.entity_form_display.paragraph.accordion.default.yml
  config/install/field.field.paragraph.accordion.field_paragraph_accordion_style.yml
  config/install/field.field.paragraph.accordion.field_paragraph_title.yml
  config/install/field.field.paragraph.accordion_content.field_paragraph_accordion_body.yml
  config/install/field.field.paragraph.accordion_content.field_paragraph_accordion_name.yml
  config/install/field.storage.paragraph.field_paragraph_accordion_style.yml
  tide_core.install
Labels: Ready for test
