Repository dpc-sdp/tide_core, pull requests merged in 2020-09, with the labels that each got.

#170 Release/1.6.8
  config/install/core.entity_form_display.paragraph.accordion.default.yml
  config/install/field.field.paragraph.accordion.field_paragraph_accordion_style.yml
  config/install/field.field.paragraph.accordion.field_paragraph_title.yml
  config/install/field.field.paragraph.accordion_content.field_paragraph_accordion_body.yml
  config/install/field.field.paragraph.accordion_content.field_paragraph_accordion_name.yml
  config/install/field.storage.node.field_landing_page_contact.yml
  config/install/field.storage.paragraph.field_paragraph_accordion_style.yml
  config/install/filter.format.admin_text.yml
  config/install/filter.format.rich_text.yml
  tide_core.install
Labels: Needs review

#171 [SDPA-2552] Add css hook alter for CKEditor to override styling for media library…
  css/ckeditor_overrides.css
  tide_core.libraries.yml
  tide_core.module
Labels: Ready for test

#174 [SDPA-4572] imports new format and editor entity
  config/optional/editor.editor.summary_text.yml
  config/optional/filter.format.summary_text.yml
  tide_core.install
Labels: Needs review

#178 [SDPA-4613] upgrade to drupal 8.8.10
  composer.json
Labels: Needs review

#176 [SDPA-4610] update permissions
  config/install/user.role.approver.yml
  config/install/user.role.editor.yml
  config/install/user.role.site_admin.yml
  tide_core.install
Labels: Ready to be merged

#175 [SDPA-4582] Added new display headings field storage.
  config/install/field.storage.node.field_node_display_headings.yml
  tide_core.info.yml
  tide_core.install
Labels: Needs review

#179 [SDPA-4569] add custom callout template as plugin
  config/optional/editor.editor.admin_text.yml
  config/optional/editor.editor.rich_text.yml
  css/ckeditor_overrides.css
  js/plugins/tide_callout/images/icon.png
  js/plugins/tide_callout/plugin.js
  src/Plugin/CKEditorPlugin/TideCallout.php
  tide_core.install
Labels: Needs review
