Repository dpc-sdp/tide_core, pull requests merged in 2022-10, with the labels that each got.

#339 Feature/srm 512 update drupal to 9.4
  composer.json
  modules/tide_paragraphs_enhanced_modal/tide_paragraphs_enhanced_modal.module
  src/Plugin/CKEditorPlugin/TideCallout.php
  src/Plugin/CKEditorPlugin/TideEmbeddedGoogleMapsButton.php
  tide_core.install
  tide_core.module
Labels: Ready to be merged

#346 [SDPAP-5301] Adding headers to unlabelled radio buttons
  tide_core.module
Labels: Needs review

#347 [SDPAP-5665] Add moderated content submenu to Content Menu
  tide_core.links.menu.yml
Labels: Needs review

#345 [SDPAP-6680] prevent create new taxonomy topics
  tide_core.install
Labels: DO NOT MERGE, Needs review
