Repository dpc-sdp/tide_core, pull requests merged in 2022-11, with the labels that each got.

#319 [SDPA-5838] Fix Dashboard Search Site Filter
  modules/tide_dashboard/src/Form/AdminContentSearchForm.php
Labels: Ready to be merged

#350 [SDPAP-5665] Add moderated content submenu to Content Menu
  config/install/user.role.editor.yml
  tests/behat/features/workflow.feature
  tide_core.install
Labels: Needs review

#348 SDPAP-5303: Navigating long menus in the CMS.
  src/Render/Element/AdminToolbar.php
  tide_core.module
Labels: Needs review

#352 Feature SDPAP-5913 addition business fields
  composer.json
  config/install/field.field.user.user.field_business_contact_number.yml
  config/install/field.field.user.user.field_business_name.yml
  config/install/field.field.user.user.field_notes.yml
  config/install/field.storage.user.field_business_contact_number.yml
  config/install/field.storage.user.field_business_name.yml
  config/install/field.storage.user.field_notes.yml
  tests/behat/features/user_business_contact.feature
  tide_core.info.yml
  tide_core.install
  tide_core.module
Labels: Needs review

#354 admin_audit_trail - Latest Release Breaks Pagination
  composer.json
Labels: Needs review

#353 [SDPAP-6292] Field not in focus not validating.
  composer.json
Labels: DO NOT MERGE, Needs review
