Repository dpc-sdp/tide_core, pull requests merged in 2022-02, with the labels that each got.

#292 [SDPSUP-3951] Fix hook implementations
  modules/tide_jira/tide_jira.module
Labels: QA complete

#280 [SDPA-5664] Redirect "Edit menu" page to menu collection on save
  tide_core.module
Labels: Needs review

#276 [SDPA-5606] Add published log to admin_audit_trail
  tide_core.module
Labels: Needs review

#282 SDPA-5448: Make the Needs Review notes field mandatory field.
  css/content_moderation.theme.css
  js/node_revision_log.js
  tide_core.libraries.yml
  tide_core.module
Labels: Needs review

#295 [SDPA-5663] Patched CMS menus page in alphabetical order
  composer.json
Labels: Ready for test

#281 [SDPA-5826] Updated Wysiwyg test.
  tests/behat/features/wysiwyg.toolbar.feature
Labels: Needs review

#297 Removed patch that is removed in recent jira rest release.
  composer.json
Labels: Needs review

#279 Feature/sdpa 5843 fix redirect node cache issue
  tide_core.module
Labels: Needs review
