Repository dpc-sdp/tide_core, pull requests merged in 2024-11, with the labels that each got.

#523 [SD-356]added content category to publication page
  modules/tide_publication/config/install/core.entity_view_display.node.publication_page.default.yml
  modules/tide_publication/config/install/field.field.node.publication_page.field_content_category.yml
  modules/tide_publication/tests/behat/features/fields.feature
  modules/tide_publication/tide_publication.install
Labels: Needs review

#536 Added hook dependency and updated config location.
  modules/tide_site/tide_site.install
  tide_core.install
Labels: Needs review

#539 Added option to ignore service if not available.
  .circleci/merge-to-reference.sh
  .github/workflows/build.yml
  src/TideSystemInfoService.php
  tide_core.services.yml
Labels: Needs review

#532 [SD-375] bypass tfa during pass reset use prlp
  modules/tide_tfa/src/Controller/TideTfaUserController.php
  modules/tide_tfa/src/Routing/TideTfaRouteSubscriber.php
  modules/tide_tfa/src/TideTfaOperation.php
  modules/tide_tfa/tide_tfa.module
  modules/tide_tfa/tide_tfa.services.yml
Labels: Needs review, Ready for test

#542 [SD-416] Fixes placeholder issue for `Header links`
  modules/tide_landing_page/config/install/field.field.paragraph.key_journeys.field_paragraph_title.yml
  modules/tide_landing_page/tide_landing_page.install
  modules/tide_landing_page/tide_landing_page.module
Labels: Needs review

#537 [SD-482] Bug in Tide captcha blocking drush cim
  modules/tide_webform/tide_webform.install
  modules/tide_webform/tide_webform.module
Labels: Needs review

#543 [SD-360] Refactor ::getHierarchy
  modules/tide_publication/src/Controller/PublicationResource.php
Labels: Needs review

#491 imported user expire settings file
  modules/tide_user_expire/config/optional/user_expire.settings.yml
  modules/tide_user_expire/tide_user_expire.install
Labels: Needs review, Stale

#554 lock scheduled_transitions to 2.5
  composer.json
Labels: Needs review

#556 [SD-535] Fixes character encoding strangeness
  modules/tide_landing_page/src/Plugin/jsonapi/FieldEnhancer/BasicTextEnhancer.php
Labels: Needs review
