Repository dpc-sdp/tide_core, pull requests merged in 2024-12, with the labels that each got.

#563 [SD-494] Enable linkset endpoint.
  modules/tide_site/tide_site.install
Labels: Needs review

#564 [SD-563] Added hook to roll out tide_data_driven_component for all cms.
  tide_core.install
Labels: Needs review

#562 [SD-551]AV-heading-not-visible
  modules/tide_paragraphs_enhanced_modal/css/paragraphs.enhanced_modal.css
Labels: Needs review, Requires more work

#561 added menu local task alter to restrict edit profile for securefile user
  modules/tide_media/tide_media.module
Labels: Ready to be merged

#557 Settings for media alias display for documents type
  composer.json
  modules/tide_media/tide_media.install
  tide_core.module
Labels: Ready for test

#568 [SD-441]add secure file widget to entity browser
  modules/tide_media/modules/tide_media_secure_files/tide_media_secure_files.install
Labels: Needs review

#567 Feature/sd 561 select field searchable checkbox
  modules/tide_webform/tide_webform.module
Labels: Ready for test
